--- 
title: "Support Vector Machine Classification of
Functional Data with Random Vertical Shifts"
author: "Tomáš Pompa"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

# SVM for Functional Data {-}

This document provides supplementary material for the article **Support Vector Machine Classification of Functional Data with Random Vertical Shifts**. It includes additional details, supporting analyses, and further explanations that complement the main findings presented in the paper.

---------------

The goal will be to apply knowledge of the Support Vector Machine (SVM) method for multivariate data to functional-type data, that is, infinite-dimensional objects. To do this, we will use both a transformation (reduction) of objects from infinite to finite dimension, followed by the use of established procedures, as well as a modification of SVM specifically for functional data, leveraging knowledge of Hilbert spaces and inner products.

Another objective will be to compare different methods for classifying functional data on real and simulated datasets. It would be beneficial to design an interesting simulation study that demonstrates the various behaviors of the considered methods.

The classification methods considered include:

- $K$ nearest neighbors (KNN),

- logistic regression (both standard (LR) and its functional modification (LR_fda)),

- linear (LDA) and quadratic (QDA) discriminant analysis,

- decision trees (DT),

- random forests (RF), and

- Support Vector Machines.

We will go through each method, starting with simulated data, and then move on to constructing a support vector machine method for functional data (SVM_fda).

The primary package in `R` for working with functional objects is `fda`. Other useful packages include `MASS`, `e1071`, `fda.usc`, `refund`, and more.
